[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "ntsulib"
version = "1.2.77"
authors = [
    { name = "NTsukine", email = "398339897@qq.com" }
]
description = "ntsulib"
dependencies = ['altgraph==0.17.4', 'backports.tarfile==1.2.0', 'certifi==2025.1.31', 'chardet==5.2.0', 'charset-normalizer==3.4.1', 'Cython==3.0.12', 'docutils==0.21.2', 'id==1.5.0', 'idna==3.10', 'importlib_metadata==8.6.1', 'jaraco.classes==3.4.0', 'jaraco.context==6.0.1', 'jaraco.functools==4.1.0', 'keyring==25.6.0', 'markdown-it-py==3.0.0', 'mdurl==0.1.2', 'more-itertools==10.6.0', 'mypy==1.6.0', 'mypy-extensions==1.0.0', 'nh3==0.2.21', 'packaging==24.2', 'pefile==2023.2.7', 'psycopg2==2.9.10', 'Pygments==2.19.1', 'pyinstaller==6.12.0', 'pyinstaller-hooks-contrib==2025.2', 'PyMySQL==1.1.1', 'PyQt5==5.15.11', 'PyQt5-Qt5==5.15.2', 'PyQt5_sip==12.17.0', 'python-a2s==1.4.1', 'pywin32-ctypes==0.2.3', 'readme_renderer==44.0', 'requests==2.32.3', 'requests-toolbelt==1.0.0', 'rfc3986==2.0.0', 'rich==13.9.4', 'tenacity==9.1.2', 'twine==6.1.0', 'typing_extensions==4.13.0', 'urllib3==2.3.0', 'zipp==3.21.0']
