[project]
name = "python_wiiu_ristretto"
version = "1.1.2"
authors = [
  { name="Joshua Peisach", email="itzswirlz2020@outlook.com" },
]
description = "Wrapper for communicating with Wii U consoles using the Ristretto API"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "asyncio",
    "aiohttp"
]
license = "GPL-3.0-only"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/ItzSwirlz/python-wiiu-ristretto"
Issues = "https://github.com/ItzSwirlz/python-wiiu-ristretto/issues"
