[tool.poetry]
name = "reflex-hosting-cli"
version = "0.1.42"
description = "Reflex Hosting CLI"
license = "Apache-2.0"
authors = ["Nikhil Rao <nikhil@reflex.dev>", "Alek Petuskey <alek@reflex.dev>"]
readme = "README.md"
homepage = "https://reflex.dev"
repository = "https://github.com/reflex-dev/reflex"
documentation = "https://reflex.dev/docs/getting-started/introduction"
keywords = ["web", "framework"]
classifiers = ["Development Status :: 4 - Beta"]
packages = [{ include = "reflex_cli" }]

[tool.poetry.dependencies]
python = "^3.9"
typer = ">=0.15.0,<1"
tabulate = "^0.9.0"
platformdirs = ">=3.10.0,<5.0"
pydantic = ">=1.10.21,<3.0"
httpx = ">=0.25.1,<1.0"
rich = ">=13.0.0,<14.0"
charset-normalizer = ">=3.3.2,<4.0.0"
pyyaml = "^6.0.2"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
pyright = ">=1.1.397"
darglint = "^1.8.1"
pytest-cov = "^6.0.0"
ruff = "^0.11.0"
pre-commit = { version = "^4.2.0", python = ">=3.8,<4.0" }
types-tabulate = "^0.9.0.3"
pytest-benchmark = "^5.0.0"
pytest-mock = "^3.10.0"
packaging = "^24.2"
coverage = "^7.6.2"

[build-system]
requires = ["poetry-core>=1.5.1"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]

[tool.ruff]

select = ["B", "D", "E", "F", "I", "SIM", "W"]

ignore = [
    "B008",
    "D203",
    "D205",
    "D213",
    "D401",
    "D406",
    "D407",
    "E501",
    "F403",
    "F405",
    "F541",
]

target-version = "py37"

[tool.ruff.per-file-ignores]

"__init__.py" = ["F401"]
"tests/*.py" = ["D100", "D103", "D104"]
"reflex/.templates/*.py" = ["D100", "D103", "D104"]
"*.pyi" = ["ALL"]
