[project]
name = "funcnodes-pyodide"
version = "0.1.11"
description = "Funcnodes in pyodide"
readme = "README.md"
classifiers = [ "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",]
requires-python = ">=3.11"
dependencies = [ "funcnodes>=0.5.36", "funcnodes-worker>=0.3.1", "funcnodes_core>=0.3.51",]

[dependency-groups]
dev = [ "build>=1.2.2.post1", "pre-commit>=4.2.0", "pytest>=8.3.4", "pytest-asyncio>=0.26.0",]

[build-system]
requires = [ "setuptools>=42",]
build-backend = "setuptools.build_meta"

[project.license]
text = "AGPL-3.0"

[tool.setuptools.package-dir]
"" = "src"

[tool.setuptools.packages.find]
where = [ "src",]
