[tool.poetry]
name = "scraipe"
version = "0.1.47"
description = "AI web scraping workflow."
readme = "README.md"
license = "MIT"
authors = ["Nibs"]
homepage = "https://github.com/snpm/scraipe"

[tool.poetry.dependencies]
python = ">=3.10,<4.0"  # Correct placement of Python version requirement
pydantic = ">=2.10.6"
pandas = ">=2.2.3"
tqdm = "*"
bs4 = "0.0.2"
aiohttp = { version = ">=3.11.16"}


# scraipe[extended] dependencies
openai = {version = "1.68.2", optional = true}
trafilatura = { version = "2.0.0",  optional = true}
telethon = { version = "1.39.0", optional = true }

# More optional dependencies for LLMs
google-genai = { version = ">=1.9.0", optional = true }

[tool.poetry.extras]
extended = [
    "telethon", "tgcrypto",
    "trafilatura", "openai",
    "google-genai"
    ]

[tool.poetry.group.dev.dependencies]
pytest = "*"
asdftimer = "*"
pytest-asyncio = "*"
pytest-cov = "*"
pytest-mock = "*"
aioresponses = "*"

[tool.poetry.group.docs.dependencies]
mkdocs = "*"
mkdocs-material = "*"
mkdocstrings = { version = "*", extras = ["python"] }
mkdocs-gen-files = "*"
mkdocs-literate-nav = "*"
mkdocs-section-index = "*"