[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]
name = "r00altcoins_monitor"
version = "0.1.7"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-coinmarketcap>=0.6",
    "prettytable",
    "r00logger",
    "r00secret",
    "r00notify",

]

[tool.uv.sources]
r00logger = { path = "../../../libs/logger", editable = true }
r00secret = { path = "../../../libs/secret", editable = true }
r00notify = { path = "../../../libs/notify", editable = true }


[project.scripts]
# на сервере запускай пакет в терминале через monitor-altcoins
monitor-altcoins = "r00altcoins_monitor.main:main"

[tool.hatch.build.targets.wheel]
# Указываем папку, которая содержит код нашего пакета
packages = ["r00altcoins_monitor"]