[project]
name = "llmada"
version = "0.1.1"
description = "负责大模型的方便调度"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "llama-index>=0.12.28",
    "openai>=1.70.0",
    "pytest>=8.3.5",
    "pytest-html>=4.1.1",
    "setuptools>=78.1.0",
]
