[project]
name = "nebu"
version = "0.1.38"
description = "A globally distributed container runtime"
readme = "README.md"
requires-python = ">=3.10.14"
dependencies = [
    "boto3>=1.37.30",
    "dill>=0.3.8",
    "openai>=1.68.2",
    "pillow>=11.1.0",
    "pydantic>=2.10.6",
    "pydantic-ai-slim[openai]>=0.0.55",
    "pysocks>=1.7.1",
    "pyyaml>=6.0.2",
    "redis[socks]>=5.0",
    "requests>=2.32.3",
]

[dependency-groups]
dev = [
    "datamodel-code-generator>=0.28.5",
    "ipykernel>=6.29.5",
    "nbformat>=5.10.4",
    "notebook>=7.3.3",
    "pytest>=8.3.5",
    "qwen-vl-utils>=0.0.10",
    "trl>=0.16.1",
]

[tool.pyright]
reportUnknownParameterType = false
reportMissingTypeArgument = false
reportUnknownMemberType = false
reportUnknownVariableType = false
reportUnknownArgumentType = false
