[project]
name = "savage-generator"
version = "0.1.3"
description = "A basic SVG generator in Python"
authors = [{name = "Jamie Gillett", email = "jamie.gillett@gmail.com"}]
readme = "README.md"
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/jamie-gillett/savage"
Issues = "https://github.com/jamie-gillett/savage/issues"

[project.optional-dependencies]
dev = [
    "pytest >= 7.0",
    "pytest-mock >= 3.0",
    "pytest-cov >= 3.0"
]

[tool.setuptools]
packages = ["savage"]
include-package-data = true

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
minversion = "6.0"
pythonpath = "."
addopts = [
    "--import-mode=importlib",
    "-ra",
    "-q",
]
testpaths = ["tests"]