[tool.poetry]
name = "nonebot-plugin-llm-plugins-call"
version = "0.2.1"
description = "LLM选择调用nonebot插件"
authors = ["Alpaca <202396298@qq.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
nonebot2 = "^2.2.0"
nonebot-adapter-onebot = "^2.2.1"
openai = "^1.55.3"
nonebot-plugin-send-anything-anywhere = "^0.7.1"
pyyaml = "^6.0.2"

[[tool.poetry.source]]
name = "tsinghua"
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple/"
default = true 

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"