[build-system]
requires = ['hatchling']
build-backend = 'hatchling.build'

[project]
name = 'ninja_import'
version = '1.0.1'
requires-python = '>=3.9' # for woodys old pipeline stuff
dependencies = []

[project.optional-dependencies]
dev = ['pytest']

[tool.pytest.ini_options]
addopts = '--doctest-modules'
testpaths = ['tests', 'ninja_import']
pythonpath = ['.']

[tool.ruff]
lint.ignore = [
   'E731', #  [ ] Do not assign a `lambda` expression, use a `def`
   'E402', #  [ ] Module level import not at top of file
   'E701', #  [ ] Multiple statements on one line (colon)
   # 'F403', #  [ ] `from Attention_module import *` used; unable to detect undefined names
   # 'F405',
   # 'F821',
   # 'F841',
]
lint.dummy-variable-rgx = '^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?)|ic)$'
target-version = 'py312'
