[build-system]
requires = [
    "hatchling>=1.27.0"
]
build-backend = "hatchling.build"

[project]
name = "pypomes_scheduling"
version = "0.4.2"
authors = [
  { name="GT Nunes", email="wisecoder01@gmail.com" }
]
description = "A collection of Python pomes, penyeach (scheduling module)"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
dependencies = [
    "APScheduler>=3.11.0",
    "pypomes_core>=2.0.6",
    "pypomes_logging>=0.6.1"
]

[project.urls]
"Homepage" = "https://github.com/TheWiseCoder/PyPomes-Scheduling"
"Bug Tracker" = "https://github.com/TheWiseCoder/PyPomes-Scheduling/issues"
