[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "FIRES"
version = "0.1.6"
description = "A package to simulate Fast Radio Bursts (FRBs) with scattering."
authors = [
    { name = "Joel Balzan", email = "jbalzan.astro@gmail.com" }
]
readme = "README.md"
license = "MIT"
requires-python = ">=3.6"
keywords = ["FRB", "scattering", "simulations"]

[tool.setuptools]
packages.find = {where = ["src"]}  # Note the corrected syntax

[tool.setuptools.package-data]
"FIRES.utils" = ["obsparams.txt", "gparams.txt"]

[project.urls]
Homepage = "https://github.com/JoelBalzan/FIRES"

[project.scripts]
FIRES = "FIRES.main:main"