[project]
name = "quantalogic_toolbox"
version = "0.5.0"
description = "A Python toolbox for Quantalogic"
long_description = "README.md"
long_description_content_type = "text/markdown"
authors = [
    {name = "RaphaÃ«l MANSUY", email = "raphael.mansuy@gmail.com"}
]
license = {text = "Apache 2.0"}
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
keywords = ["ai"]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
