[project]
name = "truck-factor-gdeluisi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Gerardo De Luisi", email = "deluisigerardo@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "pandas"
]

[tool.pytest.ini_options]
testpaths = ["tests"]
filterwarnings = "error"
xfail_strict = true

[project.scripts]
truck-factor-gdeluisi = "truck_factor_gdeluisi:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
