[tool.pyright]
# extraPaths = ["/media/storage/Files/Dayne/WebDev/Websites/proj_ceonmedia/assets/python"]

# typeCheckingMode = "strict"

# Enable extra warning for "basic" (default) type
# checking mode
reportUnusedVariable = "warning"
reportUnusedImport = "warning"
reportDuplicateImport = "warning"

# Helpers
reportUnnecessaryComparison = "warning"
reportUnnecessaryContains = "warning"
reportUnnecessaryCast = "warning"
# reportUnnecessaryIsInstance = "warning"

[tool.poetry]
name = "ceonmedia"
version = "0.2.5"
description = "Defines key data structures to be used throughout the ceonmedia pipeline"
authors = ["Dayne Kolk <daynekolk@hotmail.com>"]
readme = "README.md"
packages = [{include = "ceonmedia"}]

[tool.poetry.dependencies]
python = "^3.11"
# TODO use pypi install in prod
# marshmallow-dataclass = "^8.7.0"
# dataclass-wizard = "^0.22.3"
ceon-render = "^0.2.0"

[tool.poetry.group.test.dependencies]
pytest = "^8.1.1"

[tool.poetry.group.dev.dependencies]
# ceon-render = {path = "/mnt/FileStorage/Dayne/Web/proj_ceonmedia/assets/python/ceon_render", develop = true}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
