[project]
name = "oaas-sdk2-py"
version = "0.1.17"
description = ""
requires-python = ">=3.13"
readme = "README.md"
# authors = ["Pawissanutt <pawissanutt@gmail.com>"]
dependencies = [
    "asyncio>=3.4.3",
    "uvloop>=0.21.0; sys_platform != 'win32'",  # uvloop only for non-Windows platforms
    "betterproto[compiler]==2.0.0b7",
    "eclipse-zenoh>=1.3.3",
    "grpcio-tools>=1.71.0",
    "grpcio>=1.71.0",
    "pydantic>=2.10.6",
    "pydantic-settings>=2.8.1",
    "pyyaml>=6.0.2",
    "tsidpy>=1.1.5",
    # "oprc-py>=0.1.0"
]


[tool.uv.sources]
oprc-py = { path = "oprc-py" }

[tool.uv]
prerelease = "allow"

[tool.setuptools.packages.find]
exclude = ["protos"]

[dependency-groups]
dev = [
    "psutil>=7.0.0",
    "pytest>=8.3.5",
]

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "DEBUG"
# log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
# log_cli_date_format = "%Y-%m-%d %H:%M:%S"