[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "i6_rsync"
version = "2.0.1"
authors = [{ name = "Mahdi Mir", email = "imahdimir@gmail.com" }]
description = "make rsync between local and remote directories easy and fast"
readme = "README.md"
license = { file = "LICENSE" }
dependencies = [
    "pyperclip==1.9.0",
]

keywords = [
    "rsync",
]

[project.urls]
"Homepage" = "https://github.com/imahdimir/i6_rsync"
