[tool.pyright]
# Setup linting rules
reportUnusedVariable = "warning"
reportUnusedImport = "warning"
reportDuplicateImport = "warning"

# Helpers
reportUnnecessaryComparison = "warning"
reportUnnecessaryContains = "warning"
reportUnnecessaryCast = "warning"


[project]
name = "ceonmedia-db"
version = "0.9.1"
description = "Defines database schema and provides functionality to interact with the database."
readme = "README.md"
requires-python = ">=3.11"
authors = [
    { name = "Dayne Kolk", email = "daynekolk@hotmail.com" }
]

dependencies = [
    "psycopg2-binary>=2.9.10",
    "python-dotenv>=1.1.0",
    "sqlmodel>=0.0.24",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ruff>=0.11.4",
]
