[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "NarrativeMapper"
version = "0.3.2"
description = "NarrativeMapper is a text analysis pipeline that uncovers the dominant narratives and emotional tones within online communities."
readme = { file = "README.md", content-type = "text/markdown" }
authors = [{ name = "jontom01", email = "jonnyy.thompson@gmail.com" }]
license = { text = "Apache-2.0" }
requires-python = ">=3.8"
dependencies = [
    "pandas",
    "numpy",
    "openai",
    "umap-learn",
    "hdbscan",
    "scikit-learn",
    "python-dotenv",
    "transformers",
    "tiktoken",
    "rich",
    "torch"
]

[tool.setuptools.packages.find]
include = ["narrative_mapper*"]

[project.scripts]
narrativemapper = "narrative_mapper.narrative_mapper_cli.cli:main"