[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "RH16042UNO"
version = "0.1.1"  # Cambiar de 0.1.0 a 0.1.1 para una actualización menor
description = "Librería para resolver sistemas de ecuaciones lineales y no lineales"
readme = "README.md"
authors = [
    {name = "Kevin Rivera", email = "rh16042@ues.edu.sv"}
]
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
keywords = ["numerical methods", "linear equations", "non-linear equations"]
dependencies = [
    "numpy>=1.19.0",
]
requires-python = ">=3.7"

[project.urls]
"Homepage" = "https://github.com/keriz-rh/RH16042UNO?tab=readme-ov-file"
"Bug Tracker" = "https://github.com/username/RH16042UNO/issues"