[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dgc_modern"
version = "1.1"
description = "DGC-Modern is Best Progress Bar Library!"
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
authors = [
  { name = "DiamondGotCat", email = "diamondgotcat@gmail.com" }
]
urls = { "Homepage" = "https://github.com/DiamondGotCat/Modern" }
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent"
]

[tool.setuptools]
packages = ["dgc_modern"]
license-files = []