[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "typepeek"
version = "0.2.0"
description = "Infer type hints from runtime Python data"
readme = "README.md"
requires-python = ">=3.7"
license = { text = "MIT" }
authors = [
  { name="Le Hoang Viet", email="your_email@example.com" }
]
dependencies = []

[project.urls]
Homepage = "https://github.com/Mikyx-1/typepeek"
Repository = "https://github.com/Mikyx-1/typepeek"
