[project]
name = "lightscope"
version = "0.0.6"
authors = [
  { name = "Eric Kapitanski", email = "e@alumni.usc.edu" },
]
description = "thelightscope cybersecurity research application"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "psutil==7.0.0",
    "python-libpcap==0.5.2",
    "requests==2.32.3",
    "scapy==2.6.1",
    "urllib3==2.2.3"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "GPL-3.0-only"
license-files = ["LICENSE"]

[project.urls]
Homepage = "https://thelightscope.com"
Issues = "https://thelightscope.com"

[project.scripts]
lightscope = "lightscope.lightscope:main"

[project.entry-points.console_scripts]
lightscope = "lightscope.lightscope:main"
