[project]
name = "pyrandcracker"
version = "0.3.6"
description = "a better random cracker can predict python random lib number"
readme = "README.md"
requires-python = ">=3.5"
dependencies = [
    "numpy",
    "tqdm",
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]

[project.urls]
"Homepage" = "https://github.com/guoql666"
"Bug Tracker" = "https://github.com/guoql666/pyrandcracker/issues"
