[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "SVDClassifier"
version = "0.1.0"
authors = [
  { name="Jay Nash", email="jnash1@conncoll.edu" },
]
description = "The SVD Classifier Package"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/ConnAALL/SVDC/"
Issues = "https://github.com/ConnAALL/SVDC/issues"