[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "intake_copernicus"
description = "Intake driver for the Copernicus Marine client"
readme = "README.rst"
authors = [
  {name = "Oceanum Developers", email = "developers@oceanum.science"}
]
maintainers = [
  {name = "Oceanum Developers", email = "developers@oceanum.science"}
]
classifiers = [

]
license = {text = "MIT license"}
dependencies = [
  "copernicusmarine",
  "intake",
  "typer"
]
dynamic = ["version"]

[project.optional-dependencies]
dev = [
    "coverage",
    "ipdb",
    "ipython",
    "mypy",
    "pytest",
    "ruff",
    "sphinx",
    "tox",
    "twine"
]

[project.urls]

bugs = "https://github.com/oceanum/intake_copernicus/issues"
changelog = "https://github.com/oceanum/intake_copernicus/blob/master/changelog.md"
homepage = "https://github.com/oceanum/intake_copernicus"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.package-data]
"*" = ["*.*"]

[project.entry-points."intake.drivers"]
"copernicus_marine" = "intake_copernicus.source:CopernicusMarineSource"

# Mypy
# ----

[tool.mypy]
files = "."

# Use strict defaults
strict = true
warn_unreachable = true
warn_no_return = true

[[tool.mypy.overrides]]
# Don't require test functions to include types
module = "tests.*"
allow_untyped_defs = true
disable_error_code = "attr-defined"

